services:
  - type: web
    name: openvpn-server
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    port: 1194
    envVars:
      - key: OPENVPN_CONFIG
        value: /etc/openvpn/server.conf
    capAdd:
      - NET_ADMIN
