services:
  - type: web
    name: dockovpn
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: HOST_ADDR
        value: $(curl -s https://api.ipify.org)
    ports:
      - type: udp
        port: 1194
      - type: tcp
        port: 8080
    persistentVolumes:
      - name: openvpn_conf
        path: /opt/Dockovpn_data
